export const popularIngredients = [
  "Olive oil",
  "Vegetable oil",
  "Flour",
  "Sugar",
  "Canned tomatoes",
  "Tomato sauce",
  "Tomato paste",
  "Tuna",
  "Kidney beans",
  "Black beans",
  "Rice",
  "Pasta",
  "Lentils",
  "Potatoes",
  "Onions",
  "Garlic",
] as const;
